# rustfmt doc - https://rust-lang.github.io/rustfmt/

# JC Style
hard_tabs = true
edition = "2024"
max_width = 120
chain_width = 80
array_width = 80

use_small_heuristics = "Max"

## Unstable (nightly component rustfmt needed)
imports_granularity = "Module"



# rustup toolchain install nightly
# rustup component add rustfmt --toolchain nightly
